#%RAML 1.0
---
title: $name$
version: 1.0

protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md

mediaType: application/hal+json

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/url:
  /service:
    get:
      displayName: Get data
      description: |
        Retrieves some data.
      is: [headers.acceptHeader]
      responses:
        200:
          body:
            application/json:
              type: !include schemas/example-response.json
              example: |
                   {
                    "hello": "world"
                   }
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                unmatchedRecipient:
                  description: Invalid data provided
                  value:
                    code: NOT_FOUND
